### ISSUE TITLE
Traning Question

### ISSUE THREAD

**Issue by Yashwanthv21** [EKami/planet-amazon-deforestation#16]
Why didn't you freeze any layers of VGG before training with your data ?. Is there any advantage ? How did you decide?

**Comment by godardt** [comment]
Hey @Yashwanthv21 , sorry for the very late reply.
In fact I didn't freeze the layers in this repo because the patches from the planet amazon doesn't come close to the labels on which Imagenet was trained.

You basically have 2 options:
 - Freeze the layers and train only the last ones like the Dense layers at the bottom. In which case imo it's relevant if your problem is more or less similar to imagenet. For instance if you want to classify a breed of dogs as imagenet contains a lot of different dogs already.
 - Consider the imagenet weights as the default initialization for your model and don't freeze any layers. For instance instead of random initialization on glorot uniform you can consider using the imagenet weights as a starting point instead.

I chose to go with the latter. Ofc this is my own interpretation of how things should be decided, you should take this information with a grain of salt and I invite you to do your own research :)
